version: "3"

services:
    
  predictive-airport-signage-frontend:
    build: 
      context: .
      dockerfile: front_end.dockerfile
    container_name: predictive-airport-signage-frontend
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  predictive-airport-signage-backend:
    build: 
      context: .
      dockerfile: back_end.dockerfile
    container_name: predictive-airport-signage-backend
    environment:
      - "AERO_API_KEY=hAUtREfKvazvRdYJu7NwAEpCklCkUvxt"
      - "REFRESH_TIME=1800"
      - REDIS_HOST=redis
    depends_on:
      - redis
  
  redis: 
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    restart: always
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=redis



